language: node_js
node_js:
- 4
- 6
- node
script:
- npm run lint
- npm run test
notifications:
  email: false
  slack:
    rooms:
      secure: Dui5+PQpihnU++KqFvZKcYlCMsQY89NxxEYQIUmKwQasdjTWJVIJn1WNS0evqZPJ5Cgm4Tv3c1C40PFYyqxPAsjRLhQXfSlu+OAXfUqsZjG7j6UDe0fluMEL/I5bCK1dDQttjebEy5D/a0qmR3Mg90Y/gbhGmPGud7KQM2zzo+/wnSvT1/+L1DNIXolQNfHihcBBeaRxzKfllLLIKSlsTuyeXYlKUvEK9K4mdiAgTrdzIhD2FLfb9NwA2qCdNi2lBvf9vl8s07AC+H9n970mR/u712ceCFUJY0BBjToWeRhMNzUnmb1txIqbs3B22miiw5/tE0HIt/8Lh409TErer6rVg0OSTEaf+N/7KwOlzok0yNgFEMqbPNNo8VQjaNHHqe6OKS4jVYxY1134QmwabWtR5pbCiNcS405H7SJ5LgPRteCsnmjCQGqjiFD/G73YeQcmNqOG9875IumPcih7QjKZHRg2Tk8fd0SPEAtByIq2/9M63SdN1NFP/N9OztBf9eies5itRAtlP2ZDkwmAMVzVxHmeDUh5pok46bLpM62stEi8KXcjxrCb2qrgvkYBHZCtx0AUxX86Rs0Z7n05yg3Jl/CPJvGVzQixoDQK+e6tMjFExGI1hTK5eTrk3RcTVc+s++xCMuTA0HK8lWco9+PyCYoF784Weji2TYz5WfA=
